from scripts.forEachImage import forEachImage
from scripts.detectPedestrianOnImage import detectPedestrianOnImage
from scripts.addPedestriansToTrack import addPedestriansToTrack
from scripts.drawBoxes import drawBoxes
